local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<leader>sr', builtin.oldfiles, {})
vim.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>ls', function()
    vim.cmd('Telescope lsp_document_symbols')
end)
vim.keymap.set('n', '<leader>lw', function()
    vim.cmd('Telescope diagnostics')
end)
